### ISSUE TITLE
Dependabot

### ISSUE THREAD

**Issue by KurnakovMaksim** [KurnakovMaksim/jiraF#116]
```
version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
```
